# Alembic migration script template
"""add_daily_limit

Revision ID: 936d7ecfafe3
Revises: c0475ba7634c
Create Date: 2026-08-27 16:47:46.899322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936d7ecfafe3'
down_revision: Union[str, None] = 'c0475ba7634c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('daily_limit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('expenses', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('budgets', 'daily_limit')
    # ### end Alembic commands ###
